In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr)

numpy.ndarray

In [5]:
try:
    sample_list = [1, 2, 3, 4, 5, 6]
    sample_list += 10  # 리스트 덧셈
except Exception as e:
    print(f"{e} occurred!")

'int' object is not iterable occurred!


In [6]:
# numpy 배열 덧셈
arr2 = arr + 10
print(arr2)


[11 12 13 14 15 16]


In [7]:
try:
    arr = arr / 2  # 일반 대입 연산자는 numpy 배열에서 연산 가능
    print(arr)
    arr2 /= 2  # 복합 대입 연산자는 불가
    print(arr2)
except Exception as e:
    print(f"{e}")

[0.5 1.  1.5 2.  2.5 3. ]
Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
# 배열의 모양 변경
arr_reshaped = arr.reshape((1, 6))
print(arr_reshaped, arr.shape, arr_reshaped.shape)  # arr.shape != arr_reshaped.shape

arr = arr_reshaped.reshape((2, 3))
print(arr)

[[1 2 3 4 5 6]] (6,) (1, 6)
[[1 2 3]
 [4 5 6]]


### numpy 배열의 주요 함수들

In [10]:
print(arr)
print(f"dimension: {arr.ndim}")
print(f"size: {arr.size}")
print(f"shape: {arr.shape}")
print(f"data type: {arr.dtype}")
print(f"How many bytes for data: {arr.nbytes}")
print(f"Transpose: {arr.transpose()}")
print(f"row sum: {arr.sum(axis=0)}")
print(f"column sum: {arr.sum(axis=1)}")

[[1 2 3]
 [4 5 6]]
dimension: 2
size: 6
shape: (2, 3)
data type: int32
How many bytes for data: 24
Transpose: [[1 4]
 [2 5]
 [3 6]]
row sum: [5 7 9]
column sum: [ 6 15]


### 2가지 배열 평탄화 방법

In [11]:
 ori_arr = np.array([[1, 2, 3], [4, 5, 6]])
 print(ori_arr, "\n")
 
 arr_flat = ori_arr.flatten()  # 새로운 배열의 복사본을 반환
 print(arr_flat, "\n")
 print(ori_arr, "\n")
 
 ori_arr[1][2] = 7
 print(arr_flat, "\n")  # 'ori_arr[1][2] = 7'의 영향을 받지 않음
 print(ori_arr)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 7]]


In [12]:
 ori_arr = np.array([[1, 2, 3], [4, 5, 6]])
 print(ori_arr, "\n")
 
 arr_ravel = ori_arr.ravel()  # 가능하면 원본 배열의 뷰(view)를 반환. 원본을 그대로 사용할 수 있음
 print(arr_ravel, "\n")
 print(ori_arr, "\n")
 
 ori_arr[1][2] = 7
 print(arr_ravel, "\n")  # 'ori_arr[1][2] = 7'의 영향을 받음
 print(ori_arr)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 7] 

[[1 2 3]
 [4 5 7]]


### 다양한 형태의 배열 생성

In [13]:
print(f"make new zero array: {np.zeros((3, 2))}")
print(f"make new array which is filled ones: {np.ones((3, 2))}")
print(f"make new array which is filled you want: {np.full((3, 2), 7)}")
print(f"from 0 to 9: {np.arange(10)}")

make new zero array: [[0. 0.]
 [0. 0.]
 [0. 0.]]
make new array which is filled ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]
make new array which is filled you want: [[7 7]
 [7 7]
 [7 7]]
from 0 to 9: [0 1 2 3 4 5 6 7 8 9]


### numpy 배열의 기초 연산

In [14]:
# 사칙연산 방식

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([1, 3, 5, 2, 4, 6])

arr_add = arr1 + arr2
print(arr_add)

arr_mul2 = arr1 * 2
print(arr_mul2)

arr_mul = arr1 * arr2  # 각 자리에 맞는 원소끼리 곱셈 (element-wise)
print(arr_mul)

[ 2  5  8  6  9 12]
[ 2  4  6  8 10 12]
[ 1  6 15  8 20 36]


In [15]:
arr1 = arr1.reshape((2, 3))
arr2 = arr2.reshape((2, 3))

arr_mul = arr1 * arr2  # element-wise (행렬 곱이 아님!)
print(arr_mul)

[[ 1  6 15]
 [ 8 20 36]]


In [21]:
# numpy 함수를 사용하는 방식

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.floor_divide(arr1, arr2))  # arr1/arr2 하고 나머지 값 버림
print(np.mod(arr1, arr2))  # arr1/arr2 의 나머지

[[ 2  5  8]
 [ 6  9 12]]
[[ 0 -1 -2]
 [ 2  1  0]]
[[ 1  6 15]
 [ 8 20 36]]
[[1 0 0]
 [2 1 1]]
[[0 2 3]
 [0 1 0]]


### 행렬 곱

In [17]:
# (2, 3) 배열
A = np.array([[1, 2, 3], [4, 5, 6]])

# (3, 2) 배열
B = np.array([[7, 8], [9, 10], [11, 12]])

# 행렬 곱 (dot product)
result = np.dot(A, B)

# 또는 @ 연산자 사용
result_alt = A @ B

# 또는 np.matmul() 사용
result_matmul = np.matmul(A, B)  # np.dot(), @와 달리 np.matmul()은 다차원 배열에서도 사용 가능

print(result, "\n")
print(result_alt, "\n")
print(result_matmul)

[[ 58  64]
 [139 154]] 

[[ 58  64]
 [139 154]] 

[[ 58  64]
 [139 154]]
