In [1]:
import numpy as np

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
type(arr)

numpy.ndarray

In [11]:
try:
    sample_list = [1, 2, 3, 4, 5, 6]
    sample_list += 10  # 리스트 덧셈
except Exception as e:
    print(f"{e} occurred!")

'int' object is not iterable occurred!


In [12]:
# numpy 배열 덧셈
arr2 = arr + 10
print(arr2)


[11 12 13 14 15 16]


In [18]:
try:
    arr = arr / 2  # 일반 대입 연산자는 numpy 배열에서 연산 가능
    print(arr)
    arr2 /= 2  # 복합 대입 연산자는 불가
    print(arr2)
except Exception as e:
    print(f"{e}")

[0.5 1.  1.5 2.  2.5 3. ]
[1. 2. 3. 4. 5. 6.]
Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'


In [23]:
# 배열의 모양 변경
arr_reshaped = arr.reshape((1, 6))
print(arr_reshaped, arr.shape, arr_reshaped.shape)  # arr.shape != arr_reshaped.shape

arr_reshaped = arr_reshaped.reshape((2, 3))
print(arr_reshaped)

[[1 2 3 4 5 6]] (6,) (1, 6)
[[1 2 3]
 [4 5 6]]
